[versions]
# CONFIG
appVersion = "0.0.1"
# DEPENDENCIES
ballast = "3.0.1"
composeMultiplatform = "1.4.0-dev-wasm08"
detekt = "1.23.0"
koin = "3.4.0"
kotlin = "1.9.0-RC"
kotlinxDateTime = "0.4.0"
ktLint = "10.2.1"
multiplatformSettings = "1.0.0"
serialization = "1.5.0"
uuid = "0.7.0"

[libraries]
ballast-core = { module = "io.github.copper-leaf:ballast-core", version.ref = "ballast" }
ballast-navigation = { module = "io.github.copper-leaf:ballast-navigation", version.ref = "ballast" }
ballast-savedState = { module = "io.github.copper-leaf:ballast-saved-state", version.ref = "ballast" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }

kotlin-dateTime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDateTime" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
kotlin-uuid = { module = "com.benasher44:uuid", version.ref = "uuid" }

multiplatformSettings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatformSettings" }

